---
title: "project_instruction"
output: html_document
date: "2023-04-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
```

```{r}
#importing data
solar_annual_o <- read.csv(
  file="./Data/Net_generation_solar_for_all_sectors_annual.csv",
  header=TRUE,
  skip=4)

solar_annual_o <- na.omit(solar_annual_o)

solar_monthly_o <- read.csv(
  file="./Data/Net_generation_solar_for_all_sectors_monthly.csv",
  header=TRUE,
  skip=4)
solar_monthly_o <- solar_monthly_o[,1:2]
solar_monthly_o <- na.omit(solar_monthly_o)

wind_annual_o <- read.csv(
  file="./Data/Net_generation_wind_all_sectors_annual.csv",
  header=TRUE,
  skip=4)
wind_annual_o <- wind_annual_o[,1:2]
wind_annual_o <- na.omit(wind_annual_o)

wind_monthly_o <- read.csv(
  file="./Data/Net_generation_wind_all_sectors_monthly.csv",
  header=TRUE,
  skip=4)
wind_monthly_o <- wind_monthly_o[,1:2]
wind_monthly_o <- na.omit(wind_monthly_o )
```

```{r}
#Preparing the data - create date object and rename columns
solar_annual <- solar_annual_o %>%
  rename(solar_annual_gen = United.States...all.utility.scale.solar.thousand.megawatthours)

solar_monthly <- solar_monthly_o %>%
  rename(solar_monthly_gen = United.States...all.utility.scale.solar.thousand.megawatthours)

wind_annual <- wind_annual_o %>%
  rename(wind_annual_gen = United.States.thousand.megawatthours)

wind_monthly <- wind_monthly_o %>%
  rename(wind_monthly_gen = United.States.thousand.megawatthours)

#head(electricity_price_processed)
#summary(electricity_price_processed)
#Inspect Data
head(solar_annual)
nvar <- ncol(solar_annual) - 1
nobs <- nrow(solar_annual)
```

```{r}
ts_solar_annual <- ts(solar_annual[,2:(nvar+1)],
                  frequency=12)
ts_solar_monthly <- ts(solar_monthly[,2:(nvar+1)],frequency=12)
ts_wind_annual <- ts(wind_annual[,2:(nvar+1)],frequency=12)
ts_wind_monthly <- ts(wind_monthly[,2:(nvar+1)],frequency=12)
```

```{r}
par(mfrow=c(1,2))
ACF_Plot <- Acf(solar_annual$solar_annual_gen, lag = 5, plot = TRUE)
PACF_Plot <- Pacf(solar_annual$solar_annual_gen, lag = 5)

par(mfrow=c(1,2))
ACF_Plot <- Acf(solar_monthly$solar_monthly_gen, lag = 40, plot = TRUE)
PACF_Plot <- Pacf(solar_monthly$solar_monthly_gen, lag = 40)

par(mfrow=c(1,2))
ACF_Plot <- Acf(wind_annual$wind_annual_gen, lag = 5, plot = TRUE)
PACF_Plot <- Pacf(wind_annual$wind_annual_gen, lag = 5)

par(mfrow=c(1,2))
ACF_Plot <- Acf(wind_monthly$wind_monthly_gen, lag = 40, plot = TRUE)
PACF_Plot <- Pacf(wind_monthly$wind_monthly_gen, lag = 40)
```

```{r}
#not working, need to be fixed
TS_Plot <- 
  ggplot(electricity_price_processed, aes(x=Month, y=Residential)) +
      geom_line()
plot(TS_Plot)

decompose_solar_monthly<- decompose(ts_solar_monthly[,"solar_annual_gen"],"additive")
plot(decompose_solar_monthly)
```